print("Please enter five numbers")
a= float(input("enter number"))
b= float(input("enter number"))
c= float(input("enter number"))
d= float(input("enter number"))
e= float(input("enter number"))
average = ((a+b+c+d+e)/5)
print("The average of those numbers is:", average)
