print("Please enter five numbers")
a= int(input("enter number"))
b= int(input("enter number"))
c= int(input("enter number"))
d= int(input("enter number"))
e= int(input("enter number"))
average = ((a+b+c+d+e)/5)
print("average is,",average)
